name: foobs-app
services:
  db:
    build:
      context: ./src/sql
      dockerfile: ./Dockerfile
    container_name: db
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

  db-tests:
    build:
      context: ./src/sql
      dockerfile: ./Dockerfile
    container_name: db-tests
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - "5433:5432"